### ISSUE TITLE
[Known Bug]: Quick Reload bug (Currently Disabled!)

### ISSUE THREAD

**Issue by Vodqc123** [paulov-t/SIT.Core#100]
**Describe the bug**
In raid I quick reloaded my gun and my gun bugged ... showed in inventory no mag and couldn't aim. Could only shoot (without visual recoil.) could not loot anything whatsoever..  (also my buddy was floating while moving/running. Hope this helps king :) )
**To Reproduce**
double press r ingame.

**SIT.Core Version:**
latest

**SPT-Aki Version:**
3.5.7

**Comment by qe201020335** [comment]
seems to also happen when there is no space for the old mag. 

maybe an emergency reload bug?

**Comment by Vodqc123** [comment]
> seems to also happen when there is no space for the old mag.
> 
> maybe an emergency reload bug?

Yeah also remebering my mag was like "red" in terms of ammo left could be the reason for it
