### ISSUE TITLE
port related problem ? 

### ISSUE THREAD

**Issue by Vodqc123** [paulov-t/SIT.Core#113]
**Describe the bug**
My bro (same house) keeps crashing when trying to load into the game 
I tried with one of my buddy and everything works fine ...

**Expected behavior**
to load in and make him customize his first account

**SIT.Core Version:**
latest

**SPT-Aki Version:**
3.5.7

**Comment by SlejmUr** [comment]
Set up port number?
Set up IP address in both json?
CrashLog? ServerLog?

This would helpful. 
Otherwise I think the Problem might be one of these:

- Not installed tarkov, just file copying from A pc to B.
- Firewall issue
- Installed AKI Client Binaries.

**Comment by Vodqc123** [comment]
did the first options and everything got was good thx Slej
