### ISSUE TITLE
game stuck on "loading profile data"

### ISSUE THREAD

**Issue by Chegamonker** [paulov-t/SIT.Core#115]
**Describe the bug**
Hello. downloaded everything needed to run SIT, but for some reason the game gets stuck on loading a profile

**To Reproduce**
1. Go to 'SITCOOP/SIT.Launcher,'
2. Click on 'Launch'
3. See error

**Expected behavior**
tried to run SIT

**Screenshots**
![image](https://github.com/paulov-t/SIT.Core/assets/135656673/3f936192-b65d-4333-a396-57e8b8634f7e)

**SIT.Core Version:**
1.4.8550.40954

**SPT-Aki Version:**
3.5.7

**Logs**
Please provide the log file(s) link here (upload into pastebin,etc)

**Additional context**
the server is up and running fine, Radmin/Hamachi used

**Comment by Chegamonker** [comment]
upd: After a long wait, I got this message:
![image](https://github.com/paulov-t/SIT.Core/assets/135656673/a74087ac-2fba-4119-96c3-9a855642b3ed)

**Comment by jeremymouton** [comment]
Caused by incorrect settings in `coopConfig.json` or `http.json`, it's been documented already. 

Remember to set `useExternalIPFinder` to `false` when using a VPN.

**Comment by Chegamonker** [comment]
forgot to mention this, sorry. everything was originally set
![image](https://github.com/paulov-t/SIT.Core/assets/135656673/5d6ebc7b-caeb-4b69-a8ec-5a7e0e8a1d91)
![image](https://github.com/paulov-t/SIT.Core/assets/135656673/f1c0b7c5-2327-47c3-b70f-93589fcdfb66)

**Comment by jeremymouton** [comment]
Does it connect when using localhost? 

Other people have reported issues using Hamachi, see https://github.com/paulov-t/SIT.Core/discussions/33#discussioncomment-6081296. Try one of the suggested alternatives to Hamachi and see if it helps.

**Comment by jeremymouton** [comment]
I should point out that using Word to make these edits is asking for trouble. 

Please use Notepad or a text editor that isn't going to introduce formatting to the json files.

**Comment by Chegamonker** [comment]
![image](https://github.com/paulov-t/SIT.Core/assets/135656673/f12276e6-5c88-4491-95c9-a164c1757322)
absolutely identical problem was with localhost. I tried using radmin and everything is exactly the same

also used notepad to edit json files. the result is described above

**Comment by jeremymouton** [comment]
Since no one else is experiencing this issue, it's probably a bad installation. Please retry.

**Comment by Chegamonker** [comment]
Yes, it looks like the game is crookedly installed. Thanks for the support and sorry for the inconvenience. everything worked
