### ISSUE TITLE
SIT Config

### ISSUE THREAD

**Issue by FakePakhan** [paulov-t/SIT.Core#14]
What does this parameter do? Which way should you move it to reach lower delays?
![image](https://user-images.githubusercontent.com/47082811/236691617-7400f199-8f0d-43f7-b47c-7e2604e470b3.png)

**Comment by harmonyzt** [comment]
Less rate in MS to send player states - More bandwidth and power but more precise player states
Higher rate in MS to send player states - Less bandwidth and power but less precise player states
