### ISSUE TITLE
"Context Menu Can't be opened while searching." and other issues

### ISSUE THREAD

**Issue by Lega955** [paulov-t/SIT.Core#140]
Bug Description:
The bug seems to appear after looting a bot, both as a host and client. In certain instances, it becomes impossible to right-click on items and open the contextual menu. An error message appears on the bottom right corner of the screen stating, "Context Menu Can't be opened while searching."

Steps to Reproduce:
The bug has been observed in two separate raids, but we are not sure what causes this. The issue seems to occur after equipping a bot backpack?

1. Start the game.
2. Join a session as a host or client.
3. Engage in looting a bot.
4. After equipping a bot backpack, observe the issue occurring?

Versions:

    SIT.Core Version: Latest
    SPT-Aki Version: 3.5.7

Other issues.

 1. When a player lies down, their character shakes and makes excessive noises.
 2. Known Bug: Running animation is not displaying correctly.
 3. Possible Known Issue: The client has significantly lower FPS compared to the host. For example, the host experiences 70+ FPS in Interchange, while the client only achieves 25-35 FPS.
 4. Sometimes bots do not have weapons in their inventory. Despite shooting at you before dying ç_ç
 
 
 If i find a certain cause for the first bug reported "Context Menu Can't be opened while searching." I will edit this post.
 
 Thanks everyone!

**Comment by jeremymouton** [comment]
Thanks for the issue report. 

> When a player lies down, their character shakes and makes excessive noises.
> Known Bug: Running animation is not displaying correctly.
> Possible Known Issue: The client has significantly lower FPS compared to the host. For example, the host experiences 70+ FPS in Interchange, while the client only achieves 25-35 FPS.

All known issues, already in the tracker.

> Sometimes bots do not have weapons in their inventory. Despite shooting at you before dying ç_ç

Would you mind creating a separate issue for this one? It's easier for the maintainers to parse issues when there is one per ticket. 

Thanks.

**Comment by Lega955** [comment]
The bug "Context Menu Can't be opened while searching." it is not happening anymore so perhaps we can close this?
