### ISSUE TITLE
Unable to install SIT

### ISSUE THREAD

**Issue by Actticus** [paulov-t/SIT.Core#41]
SPT AKI Version: 3.5.6

Catch this error after Launch

![image](https://github.com/paulov-t/SIT.Core/assets/35561355/5dfb05da-ec9d-4de1-91d3-93f2f23bee56)

**Comment by ppyLEK** [comment]
Create the missing folders shown in the error, should fix it.

**Comment by Actticus** [comment]
I think, it need to be fixed, but I can close this issue
