### ISSUE TITLE
The game is stuck on the startup screen, use latest SIT.Core and game version is 0.13.0.4.22617

### ISSUE THREAD

**Issue by w123456w30w** [paulov-t/SIT.Core#42]
If I replace the Assembly-CSharp.dll file, the game will crash. If I don't replace it, the game will get stuck on the startup screen.
game version is 0.13.0.4.22617
here is consloe log:
[Message:   BepInEx] BepInEx 5.4.21.0 - EscapeFromTarkov (2023/4/7 20:26:06)
[Info   :   BepInEx] Running under Unity v0.13.0.2261
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.21.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Warning:   BepInEx] Tried to load duplicate assembly Assembly-CSharp.dll from Managed folder! Skipping...
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 2 plugins to load
[Info   :   BepInEx] Loading [kmyuhkyuk-GamePanelHUDCore 2.5.1]
[Info   :   BepInEx] Loading [SIT.Core 1.0.0]
[Error  : Unity Log] TypeLoadException: Could not load type of field 'SIT.Core.Core.Web.TarkovTransportWSInstanceHookPatch:<TarkovRequestTransportWSInstance>k__BackingField' (0) due to: Could not resolve type with token 010000ec (from typeref, class/assembly TarkovRequestTransportWS, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null) assembly:Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null type:TarkovRequestTransportWS member:(null) signature:<none>
Stack trace:
SIT.Core.Plugin.Awake () (at <7b291510e80c4b4ba026a2b3f5609b00>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()
Sirenix.Serialization.UnitySerializationInitializer:Initialize()
Sirenix.Serialization.UnitySerializationInitializer:InitializeRuntime()

[Message:   BepInEx] Chainloader startup complete
[Info   : Unity Log] Odin Serializer ArchitectureInfo initialization with defaults (all unaligned read/writes disabled).
[Info   : Unity Log] Odin Serializer detected whitelisted runtime platform WindowsPlayer and memory read test succeeded; enabling all unaligned memory read/writes.
[Info   : Unity Log] Skipped command line argument:F:\EFT-SPT\EscapeFromTarkov.exe
[Info   : Unity Log] key:token value:b1354a924a3530d29269dbda
[Info   : Unity Log] key:config value:{"BackendUrl":"http://192.168.70.2:6969","Version":"live"}
[Info   : Unity Log] PlayerLoopSystems:
UnityEngine.PlayerLoop.Initialization
        UnityEngine.PlayerLoop.Initialization+PlayerUpdateTime
        UnityEngine.PlayerLoop.Initialization+DirectorSampleTime
        UnityEngine.PlayerLoop.Initialization+AsyncUploadTimeSlicedUpdate
        UnityEngine.PlayerLoop.Initialization+SynchronizeInputs
        UnityEngine.PlayerLoop.Initialization+SynchronizeState
        UnityEngine.PlayerLoop.Initialization+XREarlyUpdate
UnityEngine.PlayerLoop.EarlyUpdate
        CustomPlayerLoopSystem.FrameCounter
        CustomPlayerLoopSystem.StartOfFrame
        UnityEngine.PlayerLoop.EarlyUpdate+PollPlayerConnection
        UnityEngine.PlayerLoop.EarlyUpdate+ProfilerStartFrame
        UnityEngine.PlayerLoop.EarlyUpdate+GpuTimestamp
        UnityEngine.PlayerLoop.EarlyUpdate+AnalyticsCoreStatsUpdate
        UnityEngine.PlayerLoop.EarlyUpdate+UnityWebRequestUpdate
        UnityEngine.PlayerLoop.EarlyUpdate+ExecuteMainThreadJobs
        UnityEngine.PlayerLoop.EarlyUpdate+ProcessMouseInWindow
        UnityEngine.PlayerLoop.EarlyUpdate+ClearIntermediateRenderers
        UnityEngine.PlayerLoop.EarlyUpdate+ClearLines
        UnityEngine.PlayerLoop.EarlyUpdate+PresentBeforeUpdate
        UnityEngine.PlayerLoop.EarlyUpdate+ResetFrameStatsAfterPresent
        UnityEngine.PlayerLoop.EarlyUpdate+UpdateAsyncReadbackManager
        UnityEngine.PlayerLoop.EarlyUpdate+UpdateStreamingManager
        UnityEngine.PlayerLoop.EarlyUpdate+UpdateTextureStreamingManager
        UnityEngine.PlayerLoop.EarlyUpdate+UpdatePreloading
        UnityEngine.PlayerLoop.EarlyUpdate+RendererNotifyInvisible
        UnityEngine.PlayerLoop.EarlyUpdate+PlayerCleanupCachedData
        UnityEngine.PlayerLoop.EarlyUpdate+UpdateMainGameViewRect
        UnityEngine.PlayerLoop.EarlyUpdate+UpdateCanvasRectTransform
        UnityEngine.PlayerLoop.EarlyUpdate+XRUpdate
        UnityEngine.PlayerLoop.EarlyUpdate+UpdateInputManager
        UnityEngine.PlayerLoop.EarlyUpdate+ProcessRemoteInput
        UnityEngine.PlayerLoop.EarlyUpdate+ScriptRunDelayedStartupFrame
        UnityEngine.PlayerLoop.EarlyUpdate+UpdateKinect
        UnityEngine.PlayerLoop.EarlyUpdate+DeliverIosPlatformEvents
        UnityEngine.PlayerLoop.EarlyUpdate+TangoUpdate
        UnityEngine.PlayerLoop.EarlyUpdate+DispatchEventQueueEvents
        UnityEngine.PlayerLoop.EarlyUpdate+PhysicsResetInterpolatedTransformPosition
        UnityEngine.PlayerLoop.EarlyUpdate+SpriteAtlasManagerUpdate
        UnityEngine.PlayerLoop.EarlyUpdate+PerformanceAnalyticsUpdate
UnityEngine.PlayerLoop.FixedUpdate
        CustomPlayerLoopSystem.StartOfFixedUpdate
        UnityEngine.PlayerLoop.FixedUpdate+ClearLines
        UnityEngine.PlayerLoop.FixedUpdate+NewInputFixedUpdate
        UnityEngine.PlayerLoop.FixedUpdate+DirectorFixedSampleTime
        UnityEngine.PlayerLoop.FixedUpdate+AudioFixedUpdate
        UnityEngine.PlayerLoop.FixedUpdate+ScriptRunBehaviourFixedUpdate
        UnityEngine.PlayerLoop.FixedUpdate+DirectorFixedUpdate
        UnityEngine.PlayerLoop.FixedUpdate+LegacyFixedAnimationUpdate
        UnityEngine.PlayerLoop.FixedUpdate+XRFixedUpdate
        UnityEngine.PlayerLoop.FixedUpdate+PhysicsFixedUpdate
        UnityEngine.PlayerLoop.FixedUpdate+Physics2DFixedUpdate
        UnityEngine.PlayerLoop.FixedUpdate+PhysicsClothFixedUpdate
        UnityEngine.PlayerLoop.FixedUpdate+DirectorFixedUpdatePostPhysics
        UnityEngine.PlayerLoop.FixedUpdate+ScriptRunDelayedFixedFrameRate
        CustomPlayerLoopSystem.EndOfFixedUpdate
UnityEngine.PlayerLoop.PreUpdate
        UnityEngine.PlayerLoop.PreUpdate+PhysicsUpdate
        UnityEngine.PlayerLoop.PreUpdate+Physics2DUpdate
        UnityEngine.PlayerLoop.PreUpdate+CheckTexFieldInput
        UnityEngine.PlayerLoop.PreUpdate+IMGUISendQueuedEvents
        UnityEngine.PlayerLoop.PreUpdate+NewInputUpdate
        UnityEngine.PlayerLoop.PreUpdate+SendMouseEvents
        UnityEngine.PlayerLoop.PreUpdate+AIUpdate
        UnityEngine.PlayerLoop.PreUpdate+WindUpdate
        UnityEngine.PlayerLoop.PreUpdate+UpdateVideo
        CustomPlayerLoopSystem.UNetUpdate
        CustomPlayerLoopSystem.GlobalEventsClear
        CustomPlayerLoopSystem.GlobalEventsApply
UnityEngine.PlayerLoop.Update
        CustomPlayerLoopSystem.StartOfUpdate
        UnityEngine.PlayerLoop.Update+ScriptRunBehaviourUpdate
        UnityEngine.PlayerLoop.Update+ScriptRunDelayedDynamicFrameRate
        UnityEngine.PlayerLoop.Update+ScriptRunDelayedTasks
        UnityEngine.PlayerLoop.Update+DirectorUpdate
        CustomPlayerLoopSystem.EndOfUpdate
UnityEngine.PlayerLoop.PreLateUpdate
        UnityEngine.PlayerLoop.PreLateUpdate+AIUpdatePostScript
        UnityEngine.PlayerLoop.PreLateUpdate+DirectorUpdateAnimationBegin
        UnityEngine.PlayerLoop.PreLateUpdate+LegacyAnimationUpdate
        UnityEngine.PlayerLoop.PreLateUpdate+DirectorUpdateAnimationEnd
        UnityEngine.PlayerLoop.PreLateUpdate+DirectorDeferredEvaluate
        UnityEngine.PlayerLoop.PreLateUpdate+EndGraphicsJobsAfterScriptUpdate
        UnityEngine.PlayerLoop.PreLateUpdate+ConstraintManagerUpdate
        UnityEngine.PlayerLoop.PreLateUpdate+ParticleSystemBeginUpdateAll
        UnityEngine.PlayerLoop.PreLateUpdate+ScriptRunBehaviourLateUpdate
UnityEngine.PlayerLoop.PostLateUpdate
        CustomPlayerLoopSystem.StartOfPostLateUpdate
        UnityEngine.PlayerLoop.PostLateUpdate+PlayerSendFrameStarted
        UnityEngine.PlayerLoop.PostLateUpdate+DirectorLateUpdate
        UnityEngine.PlayerLoop.PostLateUpdate+ScriptRunDelayedDynamicFrameRate
        UnityEngine.PlayerLoop.PostLateUpdate+PhysicsSkinnedClothBeginUpdate
        UnityEngine.PlayerLoop.PostLateUpdate+UpdateRectTransform
        UnityEngine.PlayerLoop.PostLateUpdate+PlayerUpdateCanvases
        UnityEngine.PlayerLoop.PostLateUpdate+UpdateAudio
        UnityEngine.PlayerLoop.PostLateUpdate+VFXUpdate
        UnityEngine.PlayerLoop.PostLateUpdate+ParticleSystemEndUpdateAll
        UnityEngine.PlayerLoop.PostLateUpdate+EndGraphicsJobsAfterScriptLateUpdate
        UnityEngine.PlayerLoop.PostLateUpdate+UpdateCustomRenderTextures
        UnityEngine.PlayerLoop.PostLateUpdate+UpdateAllRenderers
        UnityEngine.PlayerLoop.PostLateUpdate+EnlightenRuntimeUpdate
        UnityEngine.PlayerLoop.PostLateUpdate+UpdateAllSkinnedMeshes
        UnityEngine.PlayerLoop.PostLateUpdate+ProcessWebSendMessages
        UnityEngine.PlayerLoop.PostLateUpdate+SortingGroupsUpdate
        UnityEngine.PlayerLoop.PostLateUpdate+UpdateVideoTextures
        UnityEngine.PlayerLoop.PostLateUpdate+UpdateVideo
        UnityEngine.PlayerLoop.PostLateUpdate+DirectorRenderImage
        UnityEngine.PlayerLoop.PostLateUpdate+PlayerEmitCanvasGeometry
        UnityEngine.PlayerLoop.PostLateUpdate+PhysicsSkinnedClothFinishUpdate
        UnityEngine.PlayerLoop.PostLateUpdate+FinishFrameRendering
        UnityEngine.PlayerLoop.PostLateUpdate+BatchModeUpdate
        UnityEngine.PlayerLoop.PostLateUpdate+PlayerSendFrameComplete
        UnityEngine.PlayerLoop.PostLateUpdate+UpdateCaptureScreenshot
        UnityEngine.PlayerLoop.PostLateUpdate+PresentAfterDraw
        UnityEngine.PlayerLoop.PostLateUpdate+ClearImmediateRenderers
        UnityEngine.PlayerLoop.PostLateUpdate+PlayerSendFramePostPresent
        UnityEngine.PlayerLoop.PostLateUpdate+UpdateResolution
        UnityEngine.PlayerLoop.PostLateUpdate+InputEndFrame
        UnityEngine.PlayerLoop.PostLateUpdate+TriggerEndOfFrameCallbacks
        UnityEngine.PlayerLoop.PostLateUpdate+GUIClearEvents
        UnityEngine.PlayerLoop.PostLateUpdate+ShaderHandleErrors
        UnityEngine.PlayerLoop.PostLateUpdate+ResetInputAxis
        UnityEngine.PlayerLoop.PostLateUpdate+ThreadedLoadingDebug
        UnityEngine.PlayerLoop.PostLateUpdate+ProfilerSynchronizeStats
        UnityEngine.PlayerLoop.PostLateUpdate+MemoryFrameMaintenance
        UnityEngine.PlayerLoop.PostLateUpdate+ExecuteGameCenterCallbacks
        UnityEngine.PlayerLoop.PostLateUpdate+ProfilerEndFrame
        CustomPlayerLoopSystem.EndOfFrame

[Info   : Unity Log] Skipped command line argument:F:\EFT-SPT\EscapeFromTarkov.exe
[Info   : Unity Log] key:token value:b1354a924a3530d29269dbda
[Info   : Unity Log] key:config value:{"BackendUrl":"http://192.168.70.2:6969","Version":"live"}
[Error  : Unity Log] ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
Stack trace:
System.Reflection.Assembly.GetTypes () (at <eae584ce26bc40229c1b1aa476bfa589>:0)
.[] () (at <3a0e7d0f3365b71602257de58ea442b1>:0)
. () (at <3a0e7d0f3365b71602257de58ea442b1>:0)
..ctor () (at <3a0e7d0f3365b71602257de58ea442b1>:0)
.get_Instance () (at <3a0e7d0f3365b71602257de58ea442b1>:0)
.CreateData[T] (EFT.DataProviding.EDataLifeTime dataLifeTime) (at <3a0e7d0f3365b71602257de58ea442b1>:0)
.Initialize () (at <3a0e7d0f3365b71602257de58ea442b1>:0)
EFT.AbstractApplication.Awake () (at <3a0e7d0f3365b71602257de58ea442b1>:0)
EFT.ClientApplication`1[T].Awake () (at <3a0e7d0f3365b71602257de58ea442b1>:0)
EFT.CommonClientApplication`1[T].Awake () (at <3a0e7d0f3365b71602257de58ea442b1>:0)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
:UnityEngine.ILogHandler.LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)

[Info   :kmyuhkyuk-GamePanelHUDCore] Loaded: kmyuhkyuk-GamePanelHUDCore

**Comment by SlejmUr** [comment]
Are you sure you using the Assembly-CSharp.dll from the Release? If you using AKI's or anyones Assembly-CSharp it will not gonna work. Also maybe remove the other mod/plugin because it is not guarantined that any mod will work, because of class renames

**Comment by w123456w30w** [comment]
> Ok ignore my earlier comment...
> 
> What version of SIT.Core and server mod are you running? Is your live game up to date?

I'm using the latest release SIT.Core and Server mod, I'll check the game version later

**Comment by w123456w30w** [comment]
> Ok ignore my earlier comment...
> 
> What version of SIT.Core and server mod are you running? Is your live game up to date?

after full reinstall from bsglauncher, the game can be started but is stuck on the loading profile screen and it shows "Backend error: Cannot connect to destination host".
The game version is 0.13.0.4.23043
SPT-Aki Server is the latest release, SIT.Core and Server Mod is the latest release too.

**Comment by w123456w30w** [comment]
> Are you sure you using the Assembly-CSharp.dll from the Release? If you using AKI's or anyones Assembly-CSharp it will not gonna work. Also maybe remove the other mod/plugin because it is not guarantined that any mod will work, because of class renames

yes, I'm using this repo dll files

**Comment by w123456w30w** [comment]
here is new console output:

[Message:   BepInEx] BepInEx 5.4.21.0 - EscapeFromTarkov (2023/5/15 19:20:54)
[Info   :   BepInEx] Running under Unity v0.13.0.2304
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.21.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 2 plugins to load
[Info   :   BepInEx] Loading [kmyuhkyuk-GamePanelHUDCore 2.5.1]
[Info   :   BepInEx] Loading [SIT.Core 1.0.0]
[Info   :ModulePatch] ChangeHealth:AbstractActiveHealthController
[Info   :ModulePatch] ChangeHealth:ChangeHealth
[Warning:  HarmonyX] ChangeHydrationPatch: You should only patch implemented methods/constructors to avoid issues. Patch the declared method void AbstractActiveHealthController::ChangeHydration(float value) instead of void AbstractActiveHealthController::ChangeHydration(float value).
[Warning:  HarmonyX] ChangeEnergyPatch: You should only patch implemented methods/constructors to avoid issues. Patch the declared method void AbstractActiveHealthController::ChangeEnergy(float value) instead of void AbstractActiveHealthController::ChangeEnergy(float value).
[Info   :ModulePatch] AutoSetOfflineMatch2 Type: MatchmakerOfflineRaidScreen
[Info   :ModulePatch] AutoSetOfflineMatch2 Method: Show
[Info   :  SIT.Core] Enabling Coop Patches
[Info   :ModulePatch] LocalGameStartingPatch:LocalGame:method_3
[Warning:  HarmonyX] LocalGameStartingPatch: You should only patch implemented methods/constructors to avoid issues. Patch the declared method System.Threading.Tasks.Task EFT.BaseLocalGame<EFT.GamePlayerOwner>::method_3(EFT.Bots.BotControllerSettings botsSettings, string backendUrl, InventoryController inventoryController, Comfort.Common.Callback runCallback) instead of System.Threading.Tasks.Task EFT.BaseLocalGame<EFT.GamePlayerOwner>::method_3(EFT.Bots.BotControllerSettings botsSettings, string backendUrl, InventoryController inventoryController, Comfort.Common.Callback runCallback).
[Info   :  SIT.Core] Plugin SIT.Core is loaded!
[Message:   BepInEx] Chainloader startup complete
[Info   : Unity Log] Odin Serializer ArchitectureInfo initialization with defaults (all unaligned read/writes disabled).
[Info   : Unity Log] Odin Serializer detected whitelisted runtime platform WindowsPlayer and memory read test succeeded; enabling all unaligned memory read/writes.
[Info   : Unity Log] Skipped command line argument:D:\EFT1\EscapeFromTarkov.exe
[Info   : Unity Log] key:token value:d360ba6239425ac0fa30af0d
[Info   : Unity Log] key:config value:{"BackendUrl":"http://127.0.0.1:6969","Version":"live"}
[Info   : Unity Log] PlayerLoopSystems:
UnityEngine.PlayerLoop.Initialization
        UnityEngine.PlayerLoop.Initialization+PlayerUpdateTime
        UnityEngine.PlayerLoop.Initialization+DirectorSampleTime
        UnityEngine.PlayerLoop.Initialization+AsyncUploadTimeSlicedUpdate
        UnityEngine.PlayerLoop.Initialization+SynchronizeInputs
        UnityEngine.PlayerLoop.Initialization+SynchronizeState
        UnityEngine.PlayerLoop.Initialization+XREarlyUpdate
UnityEngine.PlayerLoop.EarlyUpdate
        CustomPlayerLoopSystem.FrameCounter
        CustomPlayerLoopSystem.StartOfFrame
        UnityEngine.PlayerLoop.EarlyUpdate+PollPlayerConnection
        UnityEngine.PlayerLoop.EarlyUpdate+ProfilerStartFrame
        UnityEngine.PlayerLoop.EarlyUpdate+GpuTimestamp
        UnityEngine.PlayerLoop.EarlyUpdate+AnalyticsCoreStatsUpdate
        UnityEngine.PlayerLoop.EarlyUpdate+UnityWebRequestUpdate
        UnityEngine.PlayerLoop.EarlyUpdate+ExecuteMainThreadJobs
        UnityEngine.PlayerLoop.EarlyUpdate+ProcessMouseInWindow
        UnityEngine.PlayerLoop.EarlyUpdate+ClearIntermediateRenderers
        UnityEngine.PlayerLoop.EarlyUpdate+ClearLines
        UnityEngine.PlayerLoop.EarlyUpdate+PresentBeforeUpdate
        UnityEngine.PlayerLoop.EarlyUpdate+ResetFrameStatsAfterPresent
        UnityEngine.PlayerLoop.EarlyUpdate+UpdateAsyncReadbackManager
        UnityEngine.PlayerLoop.EarlyUpdate+UpdateStreamingManager
        UnityEngine.PlayerLoop.EarlyUpdate+UpdateTextureStreamingManager
        UnityEngine.PlayerLoop.EarlyUpdate+UpdatePreloading
        UnityEngine.PlayerLoop.EarlyUpdate+RendererNotifyInvisible
        UnityEngine.PlayerLoop.EarlyUpdate+PlayerCleanupCachedData
        UnityEngine.PlayerLoop.EarlyUpdate+UpdateMainGameViewRect
        UnityEngine.PlayerLoop.EarlyUpdate+UpdateCanvasRectTransform
        UnityEngine.PlayerLoop.EarlyUpdate+XRUpdate
        UnityEngine.PlayerLoop.EarlyUpdate+UpdateInputManager
        UnityEngine.PlayerLoop.EarlyUpdate+ProcessRemoteInput
        UnityEngine.PlayerLoop.EarlyUpdate+ScriptRunDelayedStartupFrame
        UnityEngine.PlayerLoop.EarlyUpdate+UpdateKinect
        UnityEngine.PlayerLoop.EarlyUpdate+DeliverIosPlatformEvents
        UnityEngine.PlayerLoop.EarlyUpdate+TangoUpdate
        UnityEngine.PlayerLoop.EarlyUpdate+DispatchEventQueueEvents
        UnityEngine.PlayerLoop.EarlyUpdate+PhysicsResetInterpolatedTransformPosition
        UnityEngine.PlayerLoop.EarlyUpdate+SpriteAtlasManagerUpdate
        UnityEngine.PlayerLoop.EarlyUpdate+PerformanceAnalyticsUpdate
UnityEngine.PlayerLoop.FixedUpdate
        CustomPlayerLoopSystem.StartOfFixedUpdate
        UnityEngine.PlayerLoop.FixedUpdate+ClearLines
        UnityEngine.PlayerLoop.FixedUpdate+NewInputFixedUpdate
        UnityEngine.PlayerLoop.FixedUpdate+DirectorFixedSampleTime
        UnityEngine.PlayerLoop.FixedUpdate+AudioFixedUpdate
        UnityEngine.PlayerLoop.FixedUpdate+ScriptRunBehaviourFixedUpdate
        UnityEngine.PlayerLoop.FixedUpdate+DirectorFixedUpdate
        UnityEngine.PlayerLoop.FixedUpdate+LegacyFixedAnimationUpdate
        UnityEngine.PlayerLoop.FixedUpdate+XRFixedUpdate
        UnityEngine.PlayerLoop.FixedUpdate+PhysicsFixedUpdate
        UnityEngine.PlayerLoop.FixedUpdate+Physics2DFixedUpdate
        UnityEngine.PlayerLoop.FixedUpdate+PhysicsClothFixedUpdate
        UnityEngine.PlayerLoop.FixedUpdate+DirectorFixedUpdatePostPhysics
        UnityEngine.PlayerLoop.FixedUpdate+ScriptRunDelayedFixedFrameRate
        CustomPlayerLoopSystem.EndOfFixedUpdate
UnityEngine.PlayerLoop.PreUpdate
        UnityEngine.PlayerLoop.PreUpdate+PhysicsUpdate
        UnityEngine.PlayerLoop.PreUpdate+Physics2DUpdate
        UnityEngine.PlayerLoop.PreUpdate+CheckTexFieldInput
        UnityEngine.PlayerLoop.PreUpdate+IMGUISendQueuedEvents
        UnityEngine.PlayerLoop.PreUpdate+NewInputUpdate
        UnityEngine.PlayerLoop.PreUpdate+SendMouseEvents
        UnityEngine.PlayerLoop.PreUpdate+AIUpdate
        UnityEngine.PlayerLoop.PreUpdate+WindUpdate
        UnityEngine.PlayerLoop.PreUpdate+UpdateVideo
        CustomPlayerLoopSystem.UNetUpdate
        CustomPlayerLoopSystem.GlobalEventsClear
        CustomPlayerLoopSystem.GlobalEventsApply
UnityEngine.PlayerLoop.Update
        CustomPlayerLoopSystem.StartOfUpdate
        UnityEngine.PlayerLoop.Update+ScriptRunBehaviourUpdate
        UnityEngine.PlayerLoop.Update+ScriptRunDelayedDynamicFrameRate
        UnityEngine.PlayerLoop.Update+ScriptRunDelayedTasks
        UnityEngine.PlayerLoop.Update+DirectorUpdate
        CustomPlayerLoopSystem.EndOfUpdate
UnityEngine.PlayerLoop.PreLateUpdate
        UnityEngine.PlayerLoop.PreLateUpdate+AIUpdatePostScript
        UnityEngine.PlayerLoop.PreLateUpdate+DirectorUpdateAnimationBegin
        UnityEngine.PlayerLoop.PreLateUpdate+LegacyAnimationUpdate
        UnityEngine.PlayerLoop.PreLateUpdate+DirectorUpdateAnimationEnd
        UnityEngine.PlayerLoop.PreLateUpdate+DirectorDeferredEvaluate
        UnityEngine.PlayerLoop.PreLateUpdate+EndGraphicsJobsAfterScriptUpdate
        UnityEngine.PlayerLoop.PreLateUpdate+ConstraintManagerUpdate
        UnityEngine.PlayerLoop.PreLateUpdate+ParticleSystemBeginUpdateAll
        UnityEngine.PlayerLoop.PreLateUpdate+ScriptRunBehaviourLateUpdate
UnityEngine.PlayerLoop.PostLateUpdate
        CustomPlayerLoopSystem.StartOfPostLateUpdate
        UnityEngine.PlayerLoop.PostLateUpdate+PlayerSendFrameStarted
        UnityEngine.PlayerLoop.PostLateUpdate+DirectorLateUpdate
        UnityEngine.PlayerLoop.PostLateUpdate+ScriptRunDelayedDynamicFrameRate
        UnityEngine.PlayerLoop.PostLateUpdate+PhysicsSkinnedClothBeginUpdate
        UnityEngine.PlayerLoop.PostLateUpdate+UpdateRectTransform
        UnityEngine.PlayerLoop.PostLateUpdate+PlayerUpdateCanvases
        UnityEngine.PlayerLoop.PostLateUpdate+UpdateAudio
        UnityEngine.PlayerLoop.PostLateUpdate+VFXUpdate
        UnityEngine.PlayerLoop.PostLateUpdate+ParticleSystemEndUpdateAll
        UnityEngine.PlayerLoop.PostLateUpdate+EndGraphicsJobsAfterScriptLateUpdate
        UnityEngine.PlayerLoop.PostLateUpdate+UpdateCustomRenderTextures
        UnityEngine.PlayerLoop.PostLateUpdate+UpdateAllRenderers
        UnityEngine.PlayerLoop.PostLateUpdate+EnlightenRuntimeUpdate
        UnityEngine.PlayerLoop.PostLateUpdate+UpdateAllSkinnedMeshes
        UnityEngine.PlayerLoop.PostLateUpdate+ProcessWebSendMessages
        UnityEngine.PlayerLoop.PostLateUpdate+SortingGroupsUpdate
        UnityEngine.PlayerLoop.PostLateUpdate+UpdateVideoTextures
        UnityEngine.PlayerLoop.PostLateUpdate+UpdateVideo
        UnityEngine.PlayerLoop.PostLateUpdate+DirectorRenderImage
        UnityEngine.PlayerLoop.PostLateUpdate+PlayerEmitCanvasGeometry
        UnityEngine.PlayerLoop.PostLateUpdate+PhysicsSkinnedClothFinishUpdate
        UnityEngine.PlayerLoop.PostLateUpdate+FinishFrameRendering
        UnityEngine.PlayerLoop.PostLateUpdate+BatchModeUpdate
        UnityEngine.PlayerLoop.PostLateUpdate+PlayerSendFrameComplete
        UnityEngine.PlayerLoop.PostLateUpdate+UpdateCaptureScreenshot
        UnityEngine.PlayerLoop.PostLateUpdate+PresentAfterDraw
        UnityEngine.PlayerLoop.PostLateUpdate+ClearImmediateRenderers
        UnityEngine.PlayerLoop.PostLateUpdate+PlayerSendFramePostPresent
        UnityEngine.PlayerLoop.PostLateUpdate+UpdateResolution
        UnityEngine.PlayerLoop.PostLateUpdate+InputEndFrame
        UnityEngine.PlayerLoop.PostLateUpdate+TriggerEndOfFrameCallbacks
        UnityEngine.PlayerLoop.PostLateUpdate+GUIClearEvents
        UnityEngine.PlayerLoop.PostLateUpdate+ShaderHandleErrors
        UnityEngine.PlayerLoop.PostLateUpdate+ResetInputAxis
        UnityEngine.PlayerLoop.PostLateUpdate+ThreadedLoadingDebug
        UnityEngine.PlayerLoop.PostLateUpdate+ProfilerSynchronizeStats
        UnityEngine.PlayerLoop.PostLateUpdate+MemoryFrameMaintenance
        UnityEngine.PlayerLoop.PostLateUpdate+ExecuteGameCenterCallbacks
        UnityEngine.PlayerLoop.PostLateUpdate+ProfilerEndFrame
        CustomPlayerLoopSystem.EndOfFrame

[Info   : Unity Log] Skipped command line argument:D:\EFT1\EscapeFromTarkov.exe
[Info   : Unity Log] key:token value:d360ba6239425ac0fa30af0d
[Info   : Unity Log] key:config value:{"BackendUrl":"http://127.0.0.1:6969","Version":"live"}
[Info   :  SIT.Core] PatchConstants.CharacterControllerInstance Type:CharacterControllerSettings
[Info   :kmyuhkyuk-GamePanelHUDCore] Loaded: kmyuhkyuk-GamePanelHUDCore
[Info   :ModulePatch] Found TarkovRequestTransportHttpInstance

**Comment by ppyLEK** [comment]
Ok your game install seems fine now. Could you paste server logs? They are found in 'serverfolder'/user/logs

**Comment by w123456w30w** [comment]
> Ok your game install seems fine now. Could you paste server logs? They are found in 'serverfolder'/user/logs

I just came back and updated the SPT server from 3.5.5 to 3.5.6, and the problem has been resolved. Now I can normally run the game
