### ISSUE TITLE
Cannot find module WS in server startup with new server mod

### ISSUE THREAD

**Issue by zachmarcus1** [paulov-t/SIT.Core#44]
Have all the new repo installled and the latest server mod along with the latest release for the server will post the error below,
The application had a critical error and failed to run
Exception produced: Error: Cannot find module 'ws'
![image](https://github.com/paulov-t/SIT.Core/assets/111416037/2ed400cb-34a7-4c52-a84a-0507fc8ee241)
Have also tried new server install and keep getting the error, Any help would be appreciated :)

**Comment by RaidmaxSpace** [comment]
C:\Users\you user\node_modules\ws

You copy it

create a "node_modules" folder in  

Server\user\mods\SITCoop\src 

you paste it ws in this folder "node_modules".

**Comment by zachmarcus1** [comment]
thank you i was so confused rookie error from me my bad hahah
